// Generated by CoffeeScript 1.6.3
(function() {
  var Search, mongoose, searchSchema;

  mongoose = require('mongoose');

  mongoose.connect("mongodb://127.0.0.1:8080/test");

  searchSchema = mongoose.Schema({
    keyword: String,
    result: String
  });

  Search = mongoose.model('Search', searchSchema);

  exports.Search = Search;

}).call(this);
