// Generated by CoffeeScript 1.6.3
(function() {
  var a, b, c;

  a = function(first, second) {
    if (second) {
      return JSON.parse(first);
    }
  };

  b = {
    d: 'hello',
    e: function() {
      return 'hi';
    }
  };

  c = false;

  a();

  console.log(b);

}).call(this);
