// Generated by CoffeeScript 1.6.3
(function() {
  var Search, models;

  models = require('../models');

  exports.home = function(req, res) {
    res.render('home');
  };

  Search = models.Search;

  exports.search = function(req, res) {
    var words;
    words = req.query.words;
    return Search.findOne({
      keyword: words
    }, function(err, data) {
      if (data) {
        res.send({
          result: data.result
        });
      } else {
        res.send({
          result: "sorry! we can't find " + "<em>" + words + "</em>"
        });
      }
    });
  };

  exports.login = function(req, res) {};

  exports.register = function(req, res) {
    var User, newUser;
    User = models.User;
    newUser = new User({
      account: req.body.account,
      password: req.body.password
    });
    return newUser.save(function(err, user) {
      return res.send("Wellcome to join us" + user.account + "!!");
    });
  };

  exports.logout = function(req, res) {};

  exports.persion = function(req, res) {};

}).call(this);
