// Generated by CoffeeScript 1.6.3
(function() {
  var handlers, routes;

  handlers = require("./handlers");

  routes = function(app) {
    app.get('/', handlers.home);
    app.get('/search', handlers.search);
    app.post('/login', handlers.login);
    app.post('/logout', handlers.logout);
    app.post('/register', handlers.register);
    app.get('/persion', handlers.persion);
  };

  module.exports = routes;

}).call(this);
