// Generated by CoffeeScript 1.6.3
(function() {
  var handlers, routes;

  handlers = require("./handlers");

  routes = function(app) {
    app.get('/', handlers.home);
    app.get('/search', handlers.search);
  };

  module.exports = routes;

}).call(this);
